# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [ ]:
def same_first_and_last(list1):
    if list1[0]==list1[-1]:
        return True
    return False
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]
print(numbers_x)
print(same_first_and_last(numbers_x))
print(numbers_y)
print(same_first_and_last(numbers_y))





# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [13]:
#code here
import numpy as np
arr1=np.array([[1,2,3],
             [4,5,6]])
arr2=np.array([[7,8,9],
             [10,11,12]])
add_array=arr1+arr2
print("Elemenet wise addition of array: ")
print(add_array)
mul_array=arr1*arr2
print("Elemenet wise multiplication of array: ")
print(mul_array)

Elemenet wise addition of array: 
[[ 8 10 12]
 [14 16 18]]
Elemenet wise multiplication of array: 
[[ 7 16 27]
 [40 55 72]]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [26]:
#code here
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped=arr.reshape(3,4)
print("Reshaped array in to (3, 4): ")
print(reshaped)

array1=[[13,14,15,16],
       [17,18,19,20],
       [21,22,23,24]]
horizontally=np.concatenate([reshaped, array1], axis=1)
print("Horizontally Concatenated array: ")
print(horizontally)
vertically=np.concatenate([reshaped, array1], axis=0)
print("Vertically Concatenated array: ")
print(vertically)

Reshaped array in to (3, 4): 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Horizontally Concatenated array: 
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]
Vertically Concatenated array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [121]:
shopping_card=[]
products = {
    1: {"name": "T-shirt", "price": "15.00"},
    2: {"name": "Coffee Mug", "price": "8.00"},
    3: {"name": "Wireless Earbuds", "price": "49.99"},
    4: {"name": "Novel", "price": "19.95"},
    5: {"name": "Board Game", "price": "24.99"},
    6: {"name": "Laptop Case", "price": "35.00"},
    7: {"name": "Fitness Tracker", "price": "99.99"},
}
print("Welcome to xyz Shopping cart")
print("1. View Available products")
print("2. Add to the sopping cart")
print("3. Exit")
while True:
    choices=int(input("Enter the valid choice"))
    if choices==1:
        for product_id, product_info in products.items():
            print("Product ID: ", end='')
            print(product_id)
            print("Product Name: " + product_info["name"])
            print("Product Price: " + product_info["price"])
            print("------------------------------------------")
            print()
    elif choices==2:
        prod=int(input("Enter the product ID you want to add: "))
        for product_id, product_info in products.items():
            if prod==product_id:
                print("ID: ", end='')
                print(product_id)
                print("Name: " + product_info["name"])
                print("Price: " + product_info["price"])
                print("---------------------------------")
                confirm=int(input("Enter 1 to confirm the order: "))
                if confirm==1:
                    shopping_card.append(product_info["name"])
                    shopping_card.append(product_info["price"])
                    print("Your product has been added to cart")
    elif choices==3:
        end=input("Enter q to exit the program: ")
        print("------------------------------------------")
        if end=="q":
            print(shopping_card)
            print("GoodBye")
            print("-----------------------------------------------")
            break

Welcome to xyz Shopping cart
1. View Available products
2. Add to the sopping cart
3. Exit
Enter the valid choice1
Product ID: 1
Product Name: T-shirt
Product Price: 15.00
------------------------------------------

Product ID: 2
Product Name: Coffee Mug
Product Price: 8.00
------------------------------------------

Product ID: 3
Product Name: Wireless Earbuds
Product Price: 49.99
------------------------------------------

Product ID: 4
Product Name: Novel
Product Price: 19.95
------------------------------------------

Product ID: 5
Product Name: Board Game
Product Price: 24.99
------------------------------------------

Product ID: 6
Product Name: Laptop Case
Product Price: 35.00
------------------------------------------

Product ID: 7
Product Name: Fitness Tracker
Product Price: 99.99
------------------------------------------

Enter the valid choice2
Enter the product ID you want to add: 4
ID: 4
Name: Novel
Price: 19.95
---------------------------------
Enter 1 to confirm the or

# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [43]:
#code here
import nltk
from nltk.tokenize import word_tokenize
important_keywords=["urgent", "important", "action required", "meeting"]
promotion_keywords=["deal", "promotion", "discount"]
spam_keywords=["lottery", "prize", "free", "click here"]
important_emails=[]
promotion_emails=[]
spam_emails=[]
emails = ["Important: Action required for your account",
    "Special promotion: Get 50% off today only!",
    "Congratulations! You've won a free prize!",
    "Meeting reminder for tomorrow",
    "Limited time offer: Buy one get one free"]
for email in emails:
    if any(keywords in email.lower() for keywords in important_keywords):
        important_emails.append(email)
    elif any(keywords in email.lower() for keywords in promotion_keywords):
        promotion_emails.append(email)
    elif any(keywords in email.lower() for keywords in spam_keywords):
        spam_emails.append(email)
print("Important Email are: ")
print(important_emails)
print("Promotion Emails are:")
print(promotion_emails)
print("Spam Emails are:")
print(spam_emails)

Important Email are: 
['Important: Action required for your account', 'Meeting reminder for tomorrow']
Promotion Emails are:
['Special promotion: Get 50% off today only!']
Spam Emails are:
["Congratulations! You've won a free prize!", 'Limited time offer: Buy one get one free']


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [28]:
#code here
Translation={
    "name": "Nombre",
    "my": "mi",
    "yours": "tuya",
    "dreams": "Sueños"
}
while True:
    print("1. Find the spanish translation of english word")
    print("2. Exit the program")
    choice=int(input("Enter one of the aboce choices: "))
    if choice==1:
        word=input("Enter the english word: ")
        if word in Translation:
            print("Spanish translation of " + word + " is " + Translation[word])
        else:
            print("Spanish translation of " + word + " is not available")
    elif choice==2:
        print("Goodbye!")
        break
    else:
        print("Invalid choice")

1. Find the spanish translation of english word
2. Exit the program
Enter one of the aboce choices: 1
Enter the english word: yours
Spanish translation of yours is tuya
1. Find the spanish translation of english word
2. Exit the program
Enter one of the aboce choices: 1
Enter the english word: school
Spanish translation of school is not available
1. Find the spanish translation of english word
2. Exit the program
Enter one of the aboce choices: 5
Invalid choice
1. Find the spanish translation of english word
2. Exit the program
Enter one of the aboce choices: 2
Goodbye!


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [46]:
import pandas as pd
url="https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
data=pd.read_csv(url,sep=',',encoding='utf-8')
data

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [87]:
df=pd.DataFrame(data)
Global_Sale_sum=df["Global_Sales"].sum()
print("Sum of Global Sales = ", end='')
print(Global_Sale_sum)

Sum of Global Sales = 8920.44


In [68]:
maximum=df["Global_Sales"].idxmax()
print("Game with highest Global Sales: ", end='')
print(df.iloc[maximum]["Name"])

Game with highest Global Sales: Wii Sports


In [74]:
NA_Sales=df["NA_Sales"].mean()
print("Average NA_Sales = ", end='')
print(NA_Sales)
EU_Sales=df["EU_Sales"].mean()
print("Average EU_Sales = ", end='')
print(EU_Sales)
JP_Sales=df["JP_Sales"].mean()
print("Average JP_Sales = ", end='')
print(JP_Sales)
Other_Sales=df["Other_Sales"].mean()
print("Average Other_Sales = ", end='')
print(Other_Sales)

Average NA_Sales = 0.26466742981082064
Average EU_Sales = 0.14665200626581515
Average JP_Sales = 0.077781660441017
Average Other_Sales = 0.0480630196409206


In [73]:
print("Top 5 games according to Global Sales")
print(df.head()["Name"])

Top 5 games according to Global Sales
0                  Wii Sports
1           Super Mario Bros.
2              Mario Kart Wii
3           Wii Sports Resort
4    Pokemon Red/Pokemon Blue
Name: Name, dtype: object


In [77]:
NA_Sales_sum=df["NA_Sales"].sum()
print("Sum of NA_Sales = ", end='')
print(NA_Sales_sum)
EU_Sales_sum=df["EU_Sales"].sum()
print("Sum of EU_Sales = ", end='')
print(EU_Sales_sum)
JP_Sales_sum=df["JP_Sales"].sum()
print("Sum of JP_Sales = ", end='')
print(JP_Sales_sum)
Other_Sales_sum=df["Other_Sales"].sum()
print("Sum of Other_Sales = ", end='')
print(Other_Sales_sum)

max_NA_sales=df["NA_Sales"].idxmax()
print("Game with highest North America Sales: ", end='')
print(df.iloc[max_NA_sales]["Name"])

Sum of NA_Sales = 4392.950000000001
Sum of EU_Sales = 2434.1299999999997
Sum of JP_Sales = 1291.0200000000002
Sum of Other_Sales = 797.7500000000001
Game with highest North America Sales: Wii Sports


In [86]:
platform_sales=df.groupby('Platform')['Global_Sales'].sum()
sorted_platforms=platform_sales.sort_values(ascending=False)
print("Top 3 gaming platform according to Global Sales")
print(sorted_platforms.head(3))

Top 3 gaming platform according to Global Sales
Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [88]:
genre_sales=df.groupby('Genre')['Global_Sales'].sum()
market_share=(genre_sales/Global_Sale_sum)*100
print("Market share of each genre: ")
print(market_share)

Market share of each genre: 
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [90]:
correlation=df['NA_Sales'].corr(df['EU_Sales'])
print("Correaltion between NA_Sales and EU_Sales: ", end='')
print(correlation)

Correaltion between NA_Sales and EU_Sales: 0.7677267483702636
